version: '3.0'

networks:
  app:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  app:
    build:
      context: ..
    networks:
      - app
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    env_file: ./.env

  postgres:
    image: 'postgres:15.1-alpine'
    networks:
      - app
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '5437:5432'
    volumes:
      - ../src/main/resources/preliquibase:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
